export const ADD_USER_START = 'ADD_USER_START';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';

export const REMOVE_USER_START = 'REMOVE_USER_START';
export const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS';
export const REMOVE_USER_ERROR = 'REMOVE_USER_ERROR';

export const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const ADD_BASKET_ITEM_START = 'ADD_BASKET_ITEM_START';
export const ADD_BASKET_ITEM_SUCCESS = 'ADD_BASKET_ITEM_SUCCESS';
export const ADD_BASKET_ITEM_ERROR = 'ADD_BASKET_ITEM_ERROR';

export const INCREMENT_BASKET_ITEM_START = 'INCREMENT_BASKET_ITEM_START';
export const INCREMENT_BASKET_ITEM_SUCCESS = 'INCREMENT_BASKET_ITEM_SUCCESS';
export const INCREMENT_BASKET_ITEM_ERROR = 'INCREMENT_BASKET_ITEM_ERROR';

export const DECREMENT_BASKET_ITEM_START = 'DECREMENT_BASKET_ITEM_START';
export const DECREMENT_BASKET_ITEM_SUCCESS = 'DECREMENT_BASKET_ITEM_SUCCESS';
export const DECREMENT_BASKET_ITEM_ERROR = 'DECREMENT_BASKET_ITEM_ERROR';

export const EMPTY_BASKET_START = 'EMPTY_BASKET_START';
export const EMPTY_BASKET_SUCCESS = 'EMPTY_BASKET_SUCCESS';
export const EMPTY_BASKET_ERROR = 'EMPTY_BASKET_ERROR';

export const ADD_ORDER_START = 'ADD_ORDER_START';
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const ADD_ORDER_ERROR = 'ADD_ORDER_ERROR';

export const REMOVE_ORDER_ITEM_START = 'REMOVE_ORDER_ITEM_START';
export const REMOVE_ORDER_ITEM_SUCCESS = 'REMOVE_ORDER_ITEM_SUCCESS';
export const REMOVE_ORDER_ITEM_ERROR = 'REMOVE_ORDER_ITEM_ERROR';

export const EMPTY_ORDER_START = 'EMPTY_ORDER_START';
export const EMPTY_ORDER_SUCCESS = 'EMPTY_ORDER_SUCCESS';
export const EMPTY_ORDER_ERROR = 'EMPTY_ORDER_ERROR';